# This is a basic workflow to help you get started with Actions

name: R2-3_CI

on:
  workflow_dispatch:

env:
  DOMAIN1: ${{ vars.DOMAIN1 }}
  DOMAIN2: ${{ vars.DOMAIN2 }}
  DOMAIN3: ${{ vars.DOMAIN3 }}
  CERT_DIR: ./certs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Export Cloudflare credentials
        run: |
          echo "CF_Email=${{ secrets.CF_Email }}" >> test1.txt
          echo "CF_Key=${{ secrets.CF_Key }}" >> test1.txt
          echo "R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}" >> test1.txt
          echo "R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}" >> test1.txt
          echo "R2_BUCKET=${{ secrets.R2_BUCKET }}" >> test1.txt
          echo "R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}" >> test1.txt
          echo "1" >> test1.txt

      - name: Issue cert via Cloudflare DNS
        run: |
          cp test1.txt test2.txt
          cat test2.txt