# This is a basic workflow to help you get started with Actions

name: R2_CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          mkdir certs
          touch certs/1.txt

      - name: Upload certs to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 cp ./certs s3://${{ secrets.R2_BUCKET }}/certs/ \
            --endpoint-url ${{ secrets.R2_ENDPOINT }} \
            --recursive
